name: 张玉洁的组件-11M图片oss
description: 
keywords:
  - 张玉洁的标签
  - network
  - websocket


license: MMMMMMM                                   # GPLv2，LGPLv2.1，MIT，Apache license v2.0，BSD

logo: https://zyj666.oss-cn-hangzhou.aliyuncs.com/IMG_zyj.JPG
source_file:
  - src/*.c

build_config:
  include:
    - include
  cflag: ""                             # C 编译器所需要要的编译参数
  define:                                      # 宏定义
    - CONFIG_USING_TLS

install:
  - dest: include
    source:
      - "include/librws.h"
